// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: proto/api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusMessage) Reset() {
	*x = StatusMessage{}
	mi := &file_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMessage) ProtoMessage() {}

func (x *StatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMessage.ProtoReflect.Descriptor instead.
func (*StatusMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *StatusMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *AuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *AuthResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuthResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type DeviceRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRegisterRequest) Reset() {
	*x = DeviceRegisterRequest{}
	mi := &file_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRegisterRequest) ProtoMessage() {}

func (x *DeviceRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRegisterRequest.ProtoReflect.Descriptor instead.
func (*DeviceRegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceRegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeviceRegisterRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceRegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	LastSeen      int64                  `protobuf:"varint,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	IptvUrl       string                 `protobuf:"bytes,9,opt,name=iptv_url,json=iptvUrl,proto3" json:"iptv_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *Device) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Device) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Device) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Device) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Device) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *Device) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Device) GetIptvUrl() string {
	if x != nil {
		return x.IptvUrl
	}
	return ""
}

type DeviceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Device              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceList) Reset() {
	*x = DeviceList{}
	mi := &file_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceList) ProtoMessage() {}

func (x *DeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceList.ProtoReflect.Descriptor instead.
func (*DeviceList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceList) GetData() []*Device {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DeviceList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DeviceList) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DeviceList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DeviceList) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type DeviceUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceUrl) Reset() {
	*x = DeviceUrl{}
	mi := &file_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceUrl) ProtoMessage() {}

func (x *DeviceUrl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceUrl.ProtoReflect.Descriptor instead.
func (*DeviceUrl) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type TournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentRequest) Reset() {
	*x = TournamentRequest{}
	mi := &file_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentRequest) ProtoMessage() {}

func (x *TournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentRequest.ProtoReflect.Descriptor instead.
func (*TournamentRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *TournamentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TournamentRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type Tournament struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tournament) Reset() {
	*x = Tournament{}
	mi := &file_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tournament) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tournament) ProtoMessage() {}

func (x *Tournament) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tournament.ProtoReflect.Descriptor instead.
func (*Tournament) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *Tournament) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tournament) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Tournament) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Tournament) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tournament) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tournament) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type TournamentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournaments   []*Tournament          `protobuf:"bytes,1,rep,name=tournaments,proto3" json:"tournaments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentList) Reset() {
	*x = TournamentList{}
	mi := &file_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentList) ProtoMessage() {}

func (x *TournamentList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentList.ProtoReflect.Descriptor instead.
func (*TournamentList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *TournamentList) GetTournaments() []*Tournament {
	if x != nil {
		return x.Tournaments
	}
	return nil
}

type AssignTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      uint32                 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TournamentId  uint32                 `protobuf:"varint,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTournamentRequest) Reset() {
	*x = AssignTournamentRequest{}
	mi := &file_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTournamentRequest) ProtoMessage() {}

func (x *AssignTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTournamentRequest.ProtoReflect.Descriptor instead.
func (*AssignTournamentRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *AssignTournamentRequest) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *AssignTournamentRequest) GetTournamentId() uint32 {
	if x != nil {
		return x.TournamentId
	}
	return 0
}

type SetTournamentIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TournamentIds []uint32               `protobuf:"varint,1,rep,packed,name=tournament_ids,json=tournamentIds,proto3" json:"tournament_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTournamentIdsRequest) Reset() {
	*x = SetTournamentIdsRequest{}
	mi := &file_proto_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTournamentIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTournamentIdsRequest) ProtoMessage() {}

func (x *SetTournamentIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTournamentIdsRequest.ProtoReflect.Descriptor instead.
func (*SetTournamentIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{13}
}

func (x *SetTournamentIdsRequest) GetTournamentIds() []uint32 {
	if x != nil {
		return x.TournamentIds
	}
	return nil
}

type DeviceTournament struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeviceId      uint32                 `protobuf:"varint,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TournamentId  uint32                 `protobuf:"varint,5,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	Device        *Device                `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	Tournament    *Tournament            `protobuf:"bytes,7,opt,name=tournament,proto3" json:"tournament,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceTournament) Reset() {
	*x = DeviceTournament{}
	mi := &file_proto_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceTournament) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTournament) ProtoMessage() {}

func (x *DeviceTournament) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTournament.ProtoReflect.Descriptor instead.
func (*DeviceTournament) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{14}
}

func (x *DeviceTournament) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeviceTournament) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DeviceTournament) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *DeviceTournament) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeviceTournament) GetTournamentId() uint32 {
	if x != nil {
		return x.TournamentId
	}
	return 0
}

func (x *DeviceTournament) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *DeviceTournament) GetTournament() *Tournament {
	if x != nil {
		return x.Tournament
	}
	return nil
}

type DeviceTournamentList struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeviceTournaments []*DeviceTournament    `protobuf:"bytes,1,rep,name=device_tournaments,json=deviceTournaments,proto3" json:"device_tournaments,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeviceTournamentList) Reset() {
	*x = DeviceTournamentList{}
	mi := &file_proto_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceTournamentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTournamentList) ProtoMessage() {}

func (x *DeviceTournamentList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTournamentList.ProtoReflect.Descriptor instead.
func (*DeviceTournamentList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{15}
}

func (x *DeviceTournamentList) GetDeviceTournaments() []*DeviceTournament {
	if x != nil {
		return x.DeviceTournaments
	}
	return nil
}

type GlobalTournamentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TournamentId  uint32                 `protobuf:"varint,4,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	Tournament    *Tournament            `protobuf:"bytes,5,opt,name=tournament,proto3" json:"tournament,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalTournamentConfig) Reset() {
	*x = GlobalTournamentConfig{}
	mi := &file_proto_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalTournamentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalTournamentConfig) ProtoMessage() {}

func (x *GlobalTournamentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalTournamentConfig.ProtoReflect.Descriptor instead.
func (*GlobalTournamentConfig) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{16}
}

func (x *GlobalTournamentConfig) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GlobalTournamentConfig) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GlobalTournamentConfig) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GlobalTournamentConfig) GetTournamentId() uint32 {
	if x != nil {
		return x.TournamentId
	}
	return 0
}

func (x *GlobalTournamentConfig) GetTournament() *Tournament {
	if x != nil {
		return x.Tournament
	}
	return nil
}

type GlobalTournamentConfigList struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Configs       []*GlobalTournamentConfig `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalTournamentConfigList) Reset() {
	*x = GlobalTournamentConfigList{}
	mi := &file_proto_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalTournamentConfigList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalTournamentConfigList) ProtoMessage() {}

func (x *GlobalTournamentConfigList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalTournamentConfigList.ProtoReflect.Descriptor instead.
func (*GlobalTournamentConfigList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{17}
}

func (x *GlobalTournamentConfigList) GetConfigs() []*GlobalTournamentConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type Team struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId         int64                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	LogoUrl        string                 `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	PrimaryColor   string                 `protobuf:"bytes,4,opt,name=primary_color,json=primaryColor,proto3" json:"primary_color,omitempty"`
	SecondaryColor string                 `protobuf:"bytes,5,opt,name=secondary_color,json=secondaryColor,proto3" json:"secondary_color,omitempty"`
	TextColor      string                 `protobuf:"bytes,6,opt,name=text_color,json=textColor,proto3" json:"text_color,omitempty"`
	Name           string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_proto_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{18}
}

func (x *Team) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Team) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *Team) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *Team) GetPrimaryColor() string {
	if x != nil {
		return x.PrimaryColor
	}
	return ""
}

func (x *Team) GetSecondaryColor() string {
	if x != nil {
		return x.SecondaryColor
	}
	return ""
}

func (x *Team) GetTextColor() string {
	if x != nil {
		return x.TextColor
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SofaScoreEvent struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Id                          uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt                   string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                   string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SofaScoreEventId            int64                  `protobuf:"varint,4,opt,name=sofa_score_event_id,json=sofaScoreEventId,proto3" json:"sofa_score_event_id,omitempty"`
	Sport                       string                 `protobuf:"bytes,5,opt,name=sport,proto3" json:"sport,omitempty"`
	HomeScore                   int32                  `protobuf:"varint,6,opt,name=home_score,json=homeScore,proto3" json:"home_score,omitempty"`
	HomeTeamId                  int64                  `protobuf:"varint,7,opt,name=home_team_id,json=homeTeamId,proto3" json:"home_team_id,omitempty"`
	AwayScore                   int32                  `protobuf:"varint,8,opt,name=away_score,json=awayScore,proto3" json:"away_score,omitempty"`
	AwayTeamId                  int64                  `protobuf:"varint,9,opt,name=away_team_id,json=awayTeamId,proto3" json:"away_team_id,omitempty"`
	ScrapedAt                   int64                  `protobuf:"varint,10,opt,name=scraped_at,json=scrapedAt,proto3" json:"scraped_at,omitempty"`
	Category                    string                 `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	StartTimestamp              int64                  `protobuf:"varint,12,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	CurrentPeriodStartTimestamp int64                  `protobuf:"varint,13,opt,name=current_period_start_timestamp,json=currentPeriodStartTimestamp,proto3" json:"current_period_start_timestamp,omitempty"`
	Slug                        string                 `protobuf:"bytes,14,opt,name=slug,proto3" json:"slug,omitempty"`
	TeamHome                    *Team                  `protobuf:"bytes,15,opt,name=team_home,json=teamHome,proto3" json:"team_home,omitempty"`
	TeamAway                    *Team                  `protobuf:"bytes,16,opt,name=team_away,json=teamAway,proto3" json:"team_away,omitempty"`
	League                      *Tournament            `protobuf:"bytes,17,opt,name=league,proto3" json:"league,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SofaScoreEvent) Reset() {
	*x = SofaScoreEvent{}
	mi := &file_proto_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SofaScoreEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SofaScoreEvent) ProtoMessage() {}

func (x *SofaScoreEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SofaScoreEvent.ProtoReflect.Descriptor instead.
func (*SofaScoreEvent) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{19}
}

func (x *SofaScoreEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SofaScoreEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SofaScoreEvent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SofaScoreEvent) GetSofaScoreEventId() int64 {
	if x != nil {
		return x.SofaScoreEventId
	}
	return 0
}

func (x *SofaScoreEvent) GetSport() string {
	if x != nil {
		return x.Sport
	}
	return ""
}

func (x *SofaScoreEvent) GetHomeScore() int32 {
	if x != nil {
		return x.HomeScore
	}
	return 0
}

func (x *SofaScoreEvent) GetHomeTeamId() int64 {
	if x != nil {
		return x.HomeTeamId
	}
	return 0
}

func (x *SofaScoreEvent) GetAwayScore() int32 {
	if x != nil {
		return x.AwayScore
	}
	return 0
}

func (x *SofaScoreEvent) GetAwayTeamId() int64 {
	if x != nil {
		return x.AwayTeamId
	}
	return 0
}

func (x *SofaScoreEvent) GetScrapedAt() int64 {
	if x != nil {
		return x.ScrapedAt
	}
	return 0
}

func (x *SofaScoreEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SofaScoreEvent) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *SofaScoreEvent) GetCurrentPeriodStartTimestamp() int64 {
	if x != nil {
		return x.CurrentPeriodStartTimestamp
	}
	return 0
}

func (x *SofaScoreEvent) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SofaScoreEvent) GetTeamHome() *Team {
	if x != nil {
		return x.TeamHome
	}
	return nil
}

func (x *SofaScoreEvent) GetTeamAway() *Team {
	if x != nil {
		return x.TeamAway
	}
	return nil
}

func (x *SofaScoreEvent) GetLeague() *Tournament {
	if x != nil {
		return x.League
	}
	return nil
}

type EventsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*SofaScoreEvent      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsList) Reset() {
	*x = EventsList{}
	mi := &file_proto_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsList) ProtoMessage() {}

func (x *EventsList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsList.ProtoReflect.Descriptor instead.
func (*EventsList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{20}
}

func (x *EventsList) GetData() []*SofaScoreEvent {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EventsList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *EventsList) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EventsList) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *EventsList) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type LogPlaybackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken   string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	StartedAt     int64                  `protobuf:"varint,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogPlaybackRequest) Reset() {
	*x = LogPlaybackRequest{}
	mi := &file_proto_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPlaybackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPlaybackRequest) ProtoMessage() {}

func (x *LogPlaybackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPlaybackRequest.ProtoReflect.Descriptor instead.
func (*LogPlaybackRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{21}
}

func (x *LogPlaybackRequest) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *LogPlaybackRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LogPlaybackRequest) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type UpdatePlaybackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndedAt       int64                  `protobuf:"varint,1,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlaybackRequest) Reset() {
	*x = UpdatePlaybackRequest{}
	mi := &file_proto_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlaybackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaybackRequest) ProtoMessage() {}

func (x *UpdatePlaybackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaybackRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlaybackRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{22}
}

func (x *UpdatePlaybackRequest) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

type PlaybackLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeviceId      uint32                 `protobuf:"varint,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       int64                  `protobuf:"varint,7,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackLog) Reset() {
	*x = PlaybackLog{}
	mi := &file_proto_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackLog) ProtoMessage() {}

func (x *PlaybackLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackLog.ProtoReflect.Descriptor instead.
func (*PlaybackLog) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{23}
}

func (x *PlaybackLog) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlaybackLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PlaybackLog) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PlaybackLog) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *PlaybackLog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PlaybackLog) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *PlaybackLog) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

type PlaybackLogList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PlaybackLog         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackLogList) Reset() {
	*x = PlaybackLogList{}
	mi := &file_proto_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackLogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackLogList) ProtoMessage() {}

func (x *PlaybackLogList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackLogList.ProtoReflect.Descriptor instead.
func (*PlaybackLogList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{24}
}

func (x *PlaybackLogList) GetList() []*PlaybackLog {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PlaybackLogList) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type EventStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SofaScoreEventId int64                  `protobuf:"varint,1,opt,name=sofa_score_event_id,json=sofaScoreEventId,proto3" json:"sofa_score_event_id,omitempty"`
	ViewCount        int64                  `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventStats) Reset() {
	*x = EventStats{}
	mi := &file_proto_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStats) ProtoMessage() {}

func (x *EventStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStats.ProtoReflect.Descriptor instead.
func (*EventStats) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{25}
}

func (x *EventStats) GetSofaScoreEventId() int64 {
	if x != nil {
		return x.SofaScoreEventId
	}
	return 0
}

func (x *EventStats) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

type TopEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*EventStats          `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopEventsResponse) Reset() {
	*x = TopEventsResponse{}
	mi := &file_proto_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopEventsResponse) ProtoMessage() {}

func (x *TopEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopEventsResponse.ProtoReflect.Descriptor instead.
func (*TopEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{26}
}

func (x *TopEventsResponse) GetStats() []*EventStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ApkInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	FileName         string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize         int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	PackageName      string                 `protobuf:"bytes,6,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	VersionCode      int32                  `protobuf:"varint,7,opt,name=version_code,json=versionCode,proto3" json:"version_code,omitempty"`
	MinSdkVersion    int32                  `protobuf:"varint,8,opt,name=min_sdk_version,json=minSdkVersion,proto3" json:"min_sdk_version,omitempty"`
	TargetSdkVersion int32                  `protobuf:"varint,9,opt,name=target_sdk_version,json=targetSdkVersion,proto3" json:"target_sdk_version,omitempty"`
	DownloadToken    string                 `protobuf:"bytes,10,opt,name=download_token,json=downloadToken,proto3" json:"download_token,omitempty"`
	DownloadUrl      string                 `protobuf:"bytes,11,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsActive         bool                   `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Downloads        int32                  `protobuf:"varint,14,opt,name=downloads,proto3" json:"downloads,omitempty"`
	PanelUrl         string                 `protobuf:"bytes,15,opt,name=panel_url,json=panelUrl,proto3" json:"panel_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApkInfo) Reset() {
	*x = ApkInfo{}
	mi := &file_proto_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkInfo) ProtoMessage() {}

func (x *ApkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkInfo.ProtoReflect.Descriptor instead.
func (*ApkInfo) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{27}
}

func (x *ApkInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ApkInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ApkInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ApkInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ApkInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApkInfo) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ApkInfo) GetVersionCode() int32 {
	if x != nil {
		return x.VersionCode
	}
	return 0
}

func (x *ApkInfo) GetMinSdkVersion() int32 {
	if x != nil {
		return x.MinSdkVersion
	}
	return 0
}

func (x *ApkInfo) GetTargetSdkVersion() int32 {
	if x != nil {
		return x.TargetSdkVersion
	}
	return 0
}

func (x *ApkInfo) GetDownloadToken() string {
	if x != nil {
		return x.DownloadToken
	}
	return ""
}

func (x *ApkInfo) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ApkInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ApkInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ApkInfo) GetDownloads() int32 {
	if x != nil {
		return x.Downloads
	}
	return 0
}

func (x *ApkInfo) GetPanelUrl() string {
	if x != nil {
		return x.PanelUrl
	}
	return ""
}

type ApkList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*ApkInfo             `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApkList) Reset() {
	*x = ApkList{}
	mi := &file_proto_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApkList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkList) ProtoMessage() {}

func (x *ApkList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkList.ProtoReflect.Descriptor instead.
func (*ApkList) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{28}
}

func (x *ApkList) GetVersions() []*ApkInfo {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ApkUploadResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	FileName         string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize         int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	PackageName      string                 `protobuf:"bytes,6,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	VersionCode      int32                  `protobuf:"varint,7,opt,name=version_code,json=versionCode,proto3" json:"version_code,omitempty"`
	MinSdkVersion    int32                  `protobuf:"varint,8,opt,name=min_sdk_version,json=minSdkVersion,proto3" json:"min_sdk_version,omitempty"`
	TargetSdkVersion int32                  `protobuf:"varint,9,opt,name=target_sdk_version,json=targetSdkVersion,proto3" json:"target_sdk_version,omitempty"`
	DownloadToken    string                 `protobuf:"bytes,10,opt,name=download_token,json=downloadToken,proto3" json:"download_token,omitempty"`
	DownloadUrl      string                 `protobuf:"bytes,11,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApkUploadResponse) Reset() {
	*x = ApkUploadResponse{}
	mi := &file_proto_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApkUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkUploadResponse) ProtoMessage() {}

func (x *ApkUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkUploadResponse.ProtoReflect.Descriptor instead.
func (*ApkUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{29}
}

func (x *ApkUploadResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ApkUploadResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ApkUploadResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ApkUploadResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ApkUploadResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApkUploadResponse) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ApkUploadResponse) GetVersionCode() int32 {
	if x != nil {
		return x.VersionCode
	}
	return 0
}

func (x *ApkUploadResponse) GetMinSdkVersion() int32 {
	if x != nil {
		return x.MinSdkVersion
	}
	return 0
}

func (x *ApkUploadResponse) GetTargetSdkVersion() int32 {
	if x != nil {
		return x.TargetSdkVersion
	}
	return 0
}

func (x *ApkUploadResponse) GetDownloadToken() string {
	if x != nil {
		return x.DownloadToken
	}
	return ""
}

func (x *ApkUploadResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ApkUploadResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ApkUpdateCheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpdateAvailable  bool                   `protobuf:"varint,1,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"`
	LatestVersion    string                 `protobuf:"bytes,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	PackageName      string                 `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	VersionCode      int32                  `protobuf:"varint,4,opt,name=version_code,json=versionCode,proto3" json:"version_code,omitempty"`
	DownloadUrl      string                 `protobuf:"bytes,5,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	Description      string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	FileSize         int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MinSdkVersion    int32                  `protobuf:"varint,8,opt,name=min_sdk_version,json=minSdkVersion,proto3" json:"min_sdk_version,omitempty"`
	TargetSdkVersion int32                  `protobuf:"varint,9,opt,name=target_sdk_version,json=targetSdkVersion,proto3" json:"target_sdk_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApkUpdateCheckResponse) Reset() {
	*x = ApkUpdateCheckResponse{}
	mi := &file_proto_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApkUpdateCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkUpdateCheckResponse) ProtoMessage() {}

func (x *ApkUpdateCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkUpdateCheckResponse.ProtoReflect.Descriptor instead.
func (*ApkUpdateCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{30}
}

func (x *ApkUpdateCheckResponse) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

func (x *ApkUpdateCheckResponse) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *ApkUpdateCheckResponse) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ApkUpdateCheckResponse) GetVersionCode() int32 {
	if x != nil {
		return x.VersionCode
	}
	return 0
}

func (x *ApkUpdateCheckResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ApkUpdateCheckResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApkUpdateCheckResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ApkUpdateCheckResponse) GetMinSdkVersion() int32 {
	if x != nil {
		return x.MinSdkVersion
	}
	return 0
}

func (x *ApkUpdateCheckResponse) GetTargetSdkVersion() int32 {
	if x != nil {
		return x.TargetSdkVersion
	}
	return 0
}

type ApkVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApkVersion) Reset() {
	*x = ApkVersion{}
	mi := &file_proto_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApkVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApkVersion) ProtoMessage() {}

func (x *ApkVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApkVersion.ProtoReflect.Descriptor instead.
func (*ApkVersion) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{31}
}

func (x *ApkVersion) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ApkVersion) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_api_proto protoreflect.FileDescriptor

const file_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/api.proto\x12\tsofascore\"%\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\")\n" +
	"\rStatusMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"?\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"o\n" +
	"\fAuthResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\"w\n" +
	"\x15DeviceRegisterRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xee\x01\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x1b\n" +
	"\tlast_seen\x18\a \x01(\x03R\blastSeen\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12\x19\n" +
	"\biptv_url\x18\t \x01(\tR\aiptvUrl\"\x94\x01\n" +
	"\n" +
	"DeviceList\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.sofascore.DeviceR\x04data\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\x1d\n" +
	"\tDeviceUrl\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\";\n" +
	"\x11TournamentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"\x9a\x01\n" +
	"\n" +
	"Tournament\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\"I\n" +
	"\x0eTournamentList\x127\n" +
	"\vtournaments\x18\x01 \x03(\v2\x15.sofascore.TournamentR\vtournaments\"[\n" +
	"\x17AssignTournamentRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\rR\bdeviceId\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\rR\ftournamentId\"@\n" +
	"\x17SetTournamentIdsRequest\x12%\n" +
	"\x0etournament_ids\x18\x01 \x03(\rR\rtournamentIds\"\x84\x02\n" +
	"\x10DeviceTournament\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\rR\bdeviceId\x12#\n" +
	"\rtournament_id\x18\x05 \x01(\rR\ftournamentId\x12)\n" +
	"\x06device\x18\x06 \x01(\v2\x11.sofascore.DeviceR\x06device\x125\n" +
	"\n" +
	"tournament\x18\a \x01(\v2\x15.sofascore.TournamentR\n" +
	"tournament\"b\n" +
	"\x14DeviceTournamentList\x12J\n" +
	"\x12device_tournaments\x18\x01 \x03(\v2\x1b.sofascore.DeviceTournamentR\x11deviceTournaments\"\xc2\x01\n" +
	"\x16GlobalTournamentConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12#\n" +
	"\rtournament_id\x18\x04 \x01(\rR\ftournamentId\x125\n" +
	"\n" +
	"tournament\x18\x05 \x01(\v2\x15.sofascore.TournamentR\n" +
	"tournament\"Y\n" +
	"\x1aGlobalTournamentConfigList\x12;\n" +
	"\aconfigs\x18\x01 \x03(\v2!.sofascore.GlobalTournamentConfigR\aconfigs\"\xcb\x01\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\x12\x19\n" +
	"\blogo_url\x18\x03 \x01(\tR\alogoUrl\x12#\n" +
	"\rprimary_color\x18\x04 \x01(\tR\fprimaryColor\x12'\n" +
	"\x0fsecondary_color\x18\x05 \x01(\tR\x0esecondaryColor\x12\x1d\n" +
	"\n" +
	"text_color\x18\x06 \x01(\tR\ttextColor\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\"\xed\x04\n" +
	"\x0eSofaScoreEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12-\n" +
	"\x13sofa_score_event_id\x18\x04 \x01(\x03R\x10sofaScoreEventId\x12\x14\n" +
	"\x05sport\x18\x05 \x01(\tR\x05sport\x12\x1d\n" +
	"\n" +
	"home_score\x18\x06 \x01(\x05R\thomeScore\x12 \n" +
	"\fhome_team_id\x18\a \x01(\x03R\n" +
	"homeTeamId\x12\x1d\n" +
	"\n" +
	"away_score\x18\b \x01(\x05R\tawayScore\x12 \n" +
	"\faway_team_id\x18\t \x01(\x03R\n" +
	"awayTeamId\x12\x1d\n" +
	"\n" +
	"scraped_at\x18\n" +
	" \x01(\x03R\tscrapedAt\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\x12'\n" +
	"\x0fstart_timestamp\x18\f \x01(\x03R\x0estartTimestamp\x12C\n" +
	"\x1ecurrent_period_start_timestamp\x18\r \x01(\x03R\x1bcurrentPeriodStartTimestamp\x12\x12\n" +
	"\x04slug\x18\x0e \x01(\tR\x04slug\x12,\n" +
	"\tteam_home\x18\x0f \x01(\v2\x0f.sofascore.TeamR\bteamHome\x12,\n" +
	"\tteam_away\x18\x10 \x01(\v2\x0f.sofascore.TeamR\bteamAway\x12-\n" +
	"\x06league\x18\x11 \x01(\v2\x15.sofascore.TournamentR\x06league\"\x9c\x01\n" +
	"\n" +
	"EventsList\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.sofascore.SofaScoreEventR\x04data\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"p\n" +
	"\x12LogPlaybackRequest\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\x03R\tstartedAt\"2\n" +
	"\x15UpdatePlaybackRequest\x12\x19\n" +
	"\bended_at\x18\x01 \x01(\x03R\aendedAt\"\xcc\x01\n" +
	"\vPlaybackLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\rR\bdeviceId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12\x19\n" +
	"\bended_at\x18\a \x01(\x03R\aendedAt\"S\n" +
	"\x0fPlaybackLogList\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.sofascore.PlaybackLogR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"Z\n" +
	"\n" +
	"EventStats\x12-\n" +
	"\x13sofa_score_event_id\x18\x01 \x01(\x03R\x10sofaScoreEventId\x12\x1d\n" +
	"\n" +
	"view_count\x18\x02 \x01(\x03R\tviewCount\"@\n" +
	"\x11TopEventsResponse\x12+\n" +
	"\x05stats\x18\x01 \x03(\v2\x15.sofascore.EventStatsR\x05stats\"\xec\x03\n" +
	"\aApkInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12!\n" +
	"\fpackage_name\x18\x06 \x01(\tR\vpackageName\x12!\n" +
	"\fversion_code\x18\a \x01(\x05R\vversionCode\x12&\n" +
	"\x0fmin_sdk_version\x18\b \x01(\x05R\rminSdkVersion\x12,\n" +
	"\x12target_sdk_version\x18\t \x01(\x05R\x10targetSdkVersion\x12%\n" +
	"\x0edownload_token\x18\n" +
	" \x01(\tR\rdownloadToken\x12!\n" +
	"\fdownload_url\x18\v \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tis_active\x18\r \x01(\bR\bisActive\x12\x1c\n" +
	"\tdownloads\x18\x0e \x01(\x05R\tdownloads\x12\x1b\n" +
	"\tpanel_url\x18\x0f \x01(\tR\bpanelUrl\"9\n" +
	"\aApkList\x12.\n" +
	"\bversions\x18\x01 \x03(\v2\x12.sofascore.ApkInfoR\bversions\"\x9e\x03\n" +
	"\x11ApkUploadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12!\n" +
	"\fpackage_name\x18\x06 \x01(\tR\vpackageName\x12!\n" +
	"\fversion_code\x18\a \x01(\x05R\vversionCode\x12&\n" +
	"\x0fmin_sdk_version\x18\b \x01(\x05R\rminSdkVersion\x12,\n" +
	"\x12target_sdk_version\x18\t \x01(\x05R\x10targetSdkVersion\x12%\n" +
	"\x0edownload_token\x18\n" +
	" \x01(\tR\rdownloadToken\x12!\n" +
	"\fdownload_url\x18\v \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"\xe8\x02\n" +
	"\x16ApkUpdateCheckResponse\x12)\n" +
	"\x10update_available\x18\x01 \x01(\bR\x0fupdateAvailable\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\tR\rlatestVersion\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12!\n" +
	"\fversion_code\x18\x04 \x01(\x05R\vversionCode\x12!\n" +
	"\fdownload_url\x18\x05 \x01(\tR\vdownloadUrl\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\x12&\n" +
	"\x0fmin_sdk_version\x18\b \x01(\x05R\rminSdkVersion\x12,\n" +
	"\x12target_sdk_version\x18\t \x01(\x05R\x10targetSdkVersion\".\n" +
	"\n" +
	"ApkVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03urlB6Z4github.com/jeriveromartinez/sofascore-scrapper/pb;pbb\x06proto3"

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData []byte
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)))
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_api_proto_goTypes = []any{
	(*ErrorResponse)(nil),              // 0: sofascore.ErrorResponse
	(*StatusMessage)(nil),              // 1: sofascore.StatusMessage
	(*StatusResponse)(nil),             // 2: sofascore.StatusResponse
	(*AuthRequest)(nil),                // 3: sofascore.AuthRequest
	(*AuthResponse)(nil),               // 4: sofascore.AuthResponse
	(*DeviceRegisterRequest)(nil),      // 5: sofascore.DeviceRegisterRequest
	(*Device)(nil),                     // 6: sofascore.Device
	(*DeviceList)(nil),                 // 7: sofascore.DeviceList
	(*DeviceUrl)(nil),                  // 8: sofascore.DeviceUrl
	(*TournamentRequest)(nil),          // 9: sofascore.TournamentRequest
	(*Tournament)(nil),                 // 10: sofascore.Tournament
	(*TournamentList)(nil),             // 11: sofascore.TournamentList
	(*AssignTournamentRequest)(nil),    // 12: sofascore.AssignTournamentRequest
	(*SetTournamentIdsRequest)(nil),    // 13: sofascore.SetTournamentIdsRequest
	(*DeviceTournament)(nil),           // 14: sofascore.DeviceTournament
	(*DeviceTournamentList)(nil),       // 15: sofascore.DeviceTournamentList
	(*GlobalTournamentConfig)(nil),     // 16: sofascore.GlobalTournamentConfig
	(*GlobalTournamentConfigList)(nil), // 17: sofascore.GlobalTournamentConfigList
	(*Team)(nil),                       // 18: sofascore.Team
	(*SofaScoreEvent)(nil),             // 19: sofascore.SofaScoreEvent
	(*EventsList)(nil),                 // 20: sofascore.EventsList
	(*LogPlaybackRequest)(nil),         // 21: sofascore.LogPlaybackRequest
	(*UpdatePlaybackRequest)(nil),      // 22: sofascore.UpdatePlaybackRequest
	(*PlaybackLog)(nil),                // 23: sofascore.PlaybackLog
	(*PlaybackLogList)(nil),            // 24: sofascore.PlaybackLogList
	(*EventStats)(nil),                 // 25: sofascore.EventStats
	(*TopEventsResponse)(nil),          // 26: sofascore.TopEventsResponse
	(*ApkInfo)(nil),                    // 27: sofascore.ApkInfo
	(*ApkList)(nil),                    // 28: sofascore.ApkList
	(*ApkUploadResponse)(nil),          // 29: sofascore.ApkUploadResponse
	(*ApkUpdateCheckResponse)(nil),     // 30: sofascore.ApkUpdateCheckResponse
	(*ApkVersion)(nil),                 // 31: sofascore.ApkVersion
}
var file_proto_api_proto_depIdxs = []int32{
	6,  // 0: sofascore.DeviceList.data:type_name -> sofascore.Device
	10, // 1: sofascore.TournamentList.tournaments:type_name -> sofascore.Tournament
	6,  // 2: sofascore.DeviceTournament.device:type_name -> sofascore.Device
	10, // 3: sofascore.DeviceTournament.tournament:type_name -> sofascore.Tournament
	14, // 4: sofascore.DeviceTournamentList.device_tournaments:type_name -> sofascore.DeviceTournament
	10, // 5: sofascore.GlobalTournamentConfig.tournament:type_name -> sofascore.Tournament
	16, // 6: sofascore.GlobalTournamentConfigList.configs:type_name -> sofascore.GlobalTournamentConfig
	18, // 7: sofascore.SofaScoreEvent.team_home:type_name -> sofascore.Team
	18, // 8: sofascore.SofaScoreEvent.team_away:type_name -> sofascore.Team
	10, // 9: sofascore.SofaScoreEvent.league:type_name -> sofascore.Tournament
	19, // 10: sofascore.EventsList.data:type_name -> sofascore.SofaScoreEvent
	23, // 11: sofascore.PlaybackLogList.list:type_name -> sofascore.PlaybackLog
	25, // 12: sofascore.TopEventsResponse.stats:type_name -> sofascore.EventStats
	27, // 13: sofascore.ApkList.versions:type_name -> sofascore.ApkInfo
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}
