#!/bin/sh
set -e

# Create the dedicated system user if missing.
if ! getent passwd iptv >/dev/null 2>&1; then
    useradd --system --home-dir /opt/iptv --shell /usr/sbin/nologin iptv
fi

# Data directories the app writes to (APK uploads, team logos).
mkdir -p /opt/iptv/apk_storage /opt/iptv/image_storage
chown -R iptv:iptv /opt/iptv

# Configuration file with sane defaults. Existing files are never overwritten.
if [ ! -f /etc/iptv/env ]; then
    mkdir -p /etc/iptv
    db_password=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24 || echo "iptv-$(date +%s)")
    jwt_secret=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48 || echo "iptv-jwt-$(date +%s)")
    cat > /etc/iptv/env <<EOF
# Generated by postinst; edit before first start if needed.
API_ADDR=0.0.0.0:8080
DB_HOST=127.0.0.1
DB_PORT=3306
DB_USER=iptv
DB_PASSWORD=$db_password
DB_NAME=iptv
REDIS_URL=redis://127.0.0.1:6379/0
JWT_SECRET=$jwt_secret
APK_STORAGE_PATH=/opt/iptv/apk_storage
IMAGE_STORAGE_PATH=/opt/iptv/image_storage
SCRAPE_BATCH_SIZE=500
SCRAPE_CONCURRENCY=8
EOF
    chmod 0640 /etc/iptv/env
    chown root:iptv /etc/iptv/env
fi

# Install the systemd unit.
systemctl daemon-reload >/dev/null 2>&1 || true

# Create the application database and user when MariaDB is running locally.
if command -v mariadb >/dev/null 2>&1 \
    && (systemctl is-active --quiet mariadb 2>/dev/null || pgrep -x mariadbd >/dev/null 2>&1); then
    (
        db_name=$(grep '^DB_NAME=' /etc/iptv/env | cut -d= -f2)
        db_user=$(grep '^DB_USER=' /etc/iptv/env | cut -d= -f2)
        db_password=$(grep '^DB_PASSWORD=' /etc/iptv/env | cut -d= -f2)
        mariadb -uroot <<SQL
CREATE DATABASE IF NOT EXISTS \`$db_name\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$db_user'@'localhost' IDENTIFIED BY '$db_password';
CREATE USER IF NOT EXISTS '$db_user'@'127.0.0.1' IDENTIFIED BY '$db_password';
GRANT ALL PRIVILEGES ON \`$db_name\`.* TO '$db_user'@'localhost';
GRANT ALL PRIVILEGES ON \`$db_name\`.* TO '$db_user'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL
    ) >/dev/null 2>&1 || true
fi

# Enable and start the service.
systemctl enable iptv.service >/dev/null 2>&1 || true
systemctl start iptv.service >/dev/null 2>&1 || true

exit 0
